### ISSUE TITLE
Fix unfinished merge on FpsLogger.prefab.meta

### ISSUE THREAD

**Issue by piksu** [unioulu/gameclue#34]
See https://github.com/unioulu/gameclue/blob/master/Assets/Prefabs/ControlStructure/FpsLogger.prefab.meta

**Comment by KonH** [comment]
@piksu @JoniMatias @Kerssinen
I've fixed meta file (these changes already presented in other file, so no data missing)

**Comment by piksu** [comment]
Thank you @KonH for your contribution, happy hacktoberfest!
